/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DataMintEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveWork"
      | "createDataset"
      | "cusdToken"
      | "datasets"
      | "fundDataset"
      | "getDatasetBalance"
      | "hasSubmitted"
      | "owner"
      | "renounceOwnership"
      | "submitWork"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DatasetCreated"
      | "DatasetFunded"
      | "OwnershipTransferred"
      | "PaymentReleased"
      | "WorkSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveWork",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDataset",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "cusdToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "datasets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundDataset",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDatasetBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasSubmitted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitWork",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveWork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cusdToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "datasets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundDataset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDatasetBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasSubmitted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitWork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DatasetCreatedEvent {
  export type InputTuple = [
    datasetId: BigNumberish,
    creator: AddressLike,
    rewardPerTask: BigNumberish,
    totalRequired: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: bigint,
    creator: string,
    rewardPerTask: bigint,
    totalRequired: bigint
  ];
  export interface OutputObject {
    datasetId: bigint;
    creator: string;
    rewardPerTask: bigint;
    totalRequired: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DatasetFundedEvent {
  export type InputTuple = [datasetId: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [datasetId: bigint, amount: bigint];
  export interface OutputObject {
    datasetId: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentReleasedEvent {
  export type InputTuple = [
    datasetId: BigNumberish,
    contributor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    datasetId: bigint,
    contributor: string,
    amount: bigint
  ];
  export interface OutputObject {
    datasetId: bigint;
    contributor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WorkSubmittedEvent {
  export type InputTuple = [datasetId: BigNumberish, contributor: AddressLike];
  export type OutputTuple = [datasetId: bigint, contributor: string];
  export interface OutputObject {
    datasetId: bigint;
    contributor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataMintEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): DataMintEscrow;
  waitForDeployment(): Promise<this>;

  interface: DataMintEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveWork: TypedContractMethod<
    [_datasetId: BigNumberish, _contributor: AddressLike],
    [void],
    "nonpayable"
  >;

  createDataset: TypedContractMethod<
    [
      _datasetId: BigNumberish,
      _rewardPerTask: BigNumberish,
      _totalRequired: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  cusdToken: TypedContractMethod<[], [string], "view">;

  datasets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        rewardPerTask: bigint;
        totalRequired: bigint;
        fundedAmount: bigint;
        paidOutAmount: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  fundDataset: TypedContractMethod<
    [_datasetId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDatasetBalance: TypedContractMethod<
    [_datasetId: BigNumberish],
    [bigint],
    "view"
  >;

  hasSubmitted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  submitWork: TypedContractMethod<
    [_datasetId: BigNumberish, _contributor: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveWork"
  ): TypedContractMethod<
    [_datasetId: BigNumberish, _contributor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDataset"
  ): TypedContractMethod<
    [
      _datasetId: BigNumberish,
      _rewardPerTask: BigNumberish,
      _totalRequired: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cusdToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "datasets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean] & {
        id: bigint;
        creator: string;
        rewardPerTask: bigint;
        totalRequired: bigint;
        fundedAmount: bigint;
        paidOutAmount: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fundDataset"
  ): TypedContractMethod<
    [_datasetId: BigNumberish, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDatasetBalance"
  ): TypedContractMethod<[_datasetId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasSubmitted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitWork"
  ): TypedContractMethod<
    [_datasetId: BigNumberish, _contributor: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DatasetCreated"
  ): TypedContractEvent<
    DatasetCreatedEvent.InputTuple,
    DatasetCreatedEvent.OutputTuple,
    DatasetCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DatasetFunded"
  ): TypedContractEvent<
    DatasetFundedEvent.InputTuple,
    DatasetFundedEvent.OutputTuple,
    DatasetFundedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentReleased"
  ): TypedContractEvent<
    PaymentReleasedEvent.InputTuple,
    PaymentReleasedEvent.OutputTuple,
    PaymentReleasedEvent.OutputObject
  >;
  getEvent(
    key: "WorkSubmitted"
  ): TypedContractEvent<
    WorkSubmittedEvent.InputTuple,
    WorkSubmittedEvent.OutputTuple,
    WorkSubmittedEvent.OutputObject
  >;

  filters: {
    "DatasetCreated(uint256,address,uint256,uint256)": TypedContractEvent<
      DatasetCreatedEvent.InputTuple,
      DatasetCreatedEvent.OutputTuple,
      DatasetCreatedEvent.OutputObject
    >;
    DatasetCreated: TypedContractEvent<
      DatasetCreatedEvent.InputTuple,
      DatasetCreatedEvent.OutputTuple,
      DatasetCreatedEvent.OutputObject
    >;

    "DatasetFunded(uint256,uint256)": TypedContractEvent<
      DatasetFundedEvent.InputTuple,
      DatasetFundedEvent.OutputTuple,
      DatasetFundedEvent.OutputObject
    >;
    DatasetFunded: TypedContractEvent<
      DatasetFundedEvent.InputTuple,
      DatasetFundedEvent.OutputTuple,
      DatasetFundedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentReleased(uint256,address,uint256)": TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;
    PaymentReleased: TypedContractEvent<
      PaymentReleasedEvent.InputTuple,
      PaymentReleasedEvent.OutputTuple,
      PaymentReleasedEvent.OutputObject
    >;

    "WorkSubmitted(uint256,address)": TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
    WorkSubmitted: TypedContractEvent<
      WorkSubmittedEvent.InputTuple,
      WorkSubmittedEvent.OutputTuple,
      WorkSubmittedEvent.OutputObject
    >;
  };
}
