-- Create users table
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    wallet_address TEXT UNIQUE,
    role TEXT CHECK (role IN ('creator', 'contributor')),
    reputation INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create datasets table
CREATE TABLE IF NOT EXISTS public.datasets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id UUID REFERENCES public.users(id) NOT NULL,
    title TEXT NOT NULL,
    type TEXT CHECK (type IN ('Voice', 'Image', 'Text')) NOT NULL,
    reward_per_task DECIMAL NOT NULL,
    total_required INTEGER NOT NULL,
    completed_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'completed', 'paused')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create submissions table
CREATE TABLE IF NOT EXISTS public.submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_id BIGINT REFERENCES public.datasets(id) NOT NULL,
    user_id UUID REFERENCES public.users(id) NOT NULL,
    file_url TEXT NOT NULL,
    ai_score DECIMAL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create payments table
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT REFERENCES public.submissions(id) NOT NULL,
    wallet_address TEXT NOT NULL,
    amount DECIMAL NOT NULL,
    tx_hash TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.datasets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

-- Users policies
CREATE POLICY "Users can view their own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.users FOR UPDATE USING (auth.uid() = id);

-- Datasets policies
CREATE POLICY "Anyone can view datasets" ON public.datasets FOR SELECT USING (true);
CREATE POLICY "Creators can insert datasets" ON public.datasets FOR INSERT WITH CHECK (auth.uid() = creator_id);
CREATE POLICY "Creators can update their own datasets" ON public.datasets FOR UPDATE USING (auth.uid() = creator_id);

-- Submissions policies
CREATE POLICY "Contributors can view their own submissions" ON public.submissions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Creators can view submissions for their datasets" ON public.submissions FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.datasets
        WHERE public.datasets.id = public.submissions.dataset_id
        AND public.datasets.creator_id = auth.uid()
    )
);
CREATE POLICY "Contributors can insert submissions" ON public.submissions FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Payments policies
CREATE POLICY "Users can view their own payments" ON public.payments FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM public.submissions
        WHERE public.submissions.id = public.payments.submission_id
        AND public.submissions.user_id = auth.uid()
    )
);
